---

- hosts: localhost
  tasks:
    - name: Find all *.txt and *.yml in /opt/test and its subdirecotories recursively for Backups
      FindFile: src=/home/parham dest=/tmp/ formats={{ item }}
      with_items:
        - ".txt"
        - ".yml"
      register: result
    - debug: var=result

